# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Ecare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ecare

pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Charts'


end
